version: '3'
services:
  mariadb:
    image: mariadb
    restart: always
    container_name: mariadb
    ports:
      - '3306:3306'
    environment:
      TZ: Asia/Shanghai
      MYSQL_ROOT_PASSWORD: 你的root用户密码
      # 初始化数据库（后续的初始化 SQL 会在这个库执行）
      MYSQL_DATABASE: continew_admin
      #MYSQL_USER: 你的数据库用户名
      #MYSQL_PASSWORD: 你的数据库密码
    volumes:
      - /docker/mysql/conf:/etc/mysql
      - /docker/mysql/data:/var/lib/mysql
  redis:
    image: redis:6.2.7
    restart: always
    container_name: redis
    ports:
      - '6379:6379'
    environment:
      TZ: Asia/Shanghai
    volumes:
      - /docker/redis/conf/redis.conf:/usr/local/redis/config/redis.conf
      - /docker/redis/data:/data
      - /docker/redis/logs:/logs
    command: 'redis-server /usr/local/redis/config/redis.conf --appendonly yes --requirepass 123456'
  continew-admin-server:
    build: ./continew-admin
    restart: always
    container_name: continew-admin-server
    ports:
      - '18000:18000'
    environment:
      TZ: Asia/Shanghai
      DB_HOST: 172.17.0.1
      DB_PORT: 3306
      DB_USER: 你的数据库用户名
      DB_PWD: 你的数据库密码
      DB_NAME: continew_admin
      REDIS_HOST: 172.17.0.1
      REDIS_PORT: 6379
      REDIS_PWD: 你的 Redis 密码
      REDIS_DB: 你的 Redis 数据库索引
    volumes:
      - /docker/continew-admin/data/file:/data/file
      - /docker/continew-admin/data/avatar:/data/avatar
      - /docker/continew-admin/logs:/logs
    depends_on:
      - redis
      - mariadb
  nginx:
    image: nginx:1.22.1
    restart: always
    container_name: nginx
    ports:
      - '80:80'
      - '443:443'
    environment:
      TZ: Asia/Shanghai
    volumes:
      - /docker/nginx/conf/nginx.conf:/etc/nginx/nginx.conf
      - /docker/nginx/cert:/etc/nginx/cert
      - /docker/continew-admin/web:/usr/share/nginx/html
      - /docker/nginx/logs:/var/log/nginx
