--- ### 项目配置
continew-admin:
  # 名称
  name: ContiNew-Admin
  # 应用名称
  appName: @project.name@
  # 版本
  version: @project.version@

--- ### 日志配置（重叠部分，优先级高于 logback-spring.xml 中的配置）
logging:
  level:
    top.charles7c: @logging.level@
  file:
    path: @logging.file.path@
  config: classpath:logback-spring.xml

--- ### 服务器配置
server:
  servlet:
    # 应用访问路径
    context-path: /
  ## Undertow 服务器配置
  undertow:
    # HTTP POST 请求内容的大小上限（默认 -1 不限制）
    max-http-post-size: -1
    # 以下的配置会影响 buffer，这些 buffer 会用于服务器连接的 IO 操作，有点类似 Netty 的池化内存管理
    # 每块 buffer的空间大小（越小的空间被利用越充分，不要设置太大，以免影响其他应用，合适即可）
    buffer-size: 512
    # 是否分配的直接内存（NIO 直接分配的堆外内存）
    direct-buffers: true
    threads:
      # 设置 IO 线程数，它主要执行非阻塞的任务，它们会负责多个连接（默认每个 CPU 核心一个线程）
      io: 8
      # 阻塞任务线程池，当执行类似 Servlet 请求阻塞操作，Undertow 会从这个线程池中取得线程（它的值设置取决于系统的负载）
      worker: 256

--- ### Spring 配置
spring:
  application:
    name: ${continew-admin.appName}
  ## 环境配置
  profiles:
    # 启用的环境
    # 配合 Maven Profile 选择不同配置文件进行启动，在 IntelliJ IDEA 右侧 Maven 工具窗口可以快速切换环境
    active: @profiles.active@
  ## JSON 配置
  jackson:
    # 时区配置
    time-zone: GMT+8
    # 日期格式化
    date-format: yyyy-MM-dd HH:mm:ss
    # 序列化配置（Bean -> JSON）
    serialization:
      # 是否格式化输出
      indent_output: false
      # 忽略无法转换的对象
      fail_on_empty_beans: false
    # 反序列化配置（JSON -> Bean）
    deserialization:
      # 忽略 JSON 中不存在的属性
      fail_on_unknown_properties: false