--- ### 代码生成器配置
generator:
  # 排除数据表
  excludeTables:
    - DATABASECHANGELOG
    - DATABASECHANGELOGLOCK
    - gen_config
    - gen_field_config
  # 模板配置
  templateConfigs:
    DO:
      # 模板路径
      templatePath: generator/Entity.ftl
      # 包名称
      packageName: model.entity
      # 排除字段
      excludeFields:
        - id
        - createUser
        - createTime
        - updateUser
        - updateTime
    Query:
      templatePath: generator/Query.ftl
      packageName: model.query
    Req:
      templatePath: generator/Req.ftl
      packageName: model.req
    Resp:
      templatePath: generator/Resp.ftl
      packageName: model.resp
      excludeFields:
        - id
        - createUser
        - createTime
    DetailResp:
      templatePath: generator/DetailResp.ftl
      packageName: model.resp
      excludeFields:
        - id
        - createUser
        - createTime
        - updateUser
        - updateTime
    Mapper:
      templatePath: generator/Mapper.ftl
      packageName: mapper
    Service:
      templatePath: generator/Service.ftl
      packageName: service
    ServiceImpl:
      templatePath: generator/ServiceImpl.ftl
      packageName: service.impl
    Controller:
      templatePath: generator/Controller.ftl
      packageName: controller